<?php

namespace Database\Seeders;

use App\Models\Employe;
use Illuminate\Database\Seeder;

class EmployeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employes = [
            // Entreprise 1: Benin Security (ID 1)
            [
                'entreprise_id' => 1,
                'matricule' => 'BSS-001',
                'civilite' => 'M',
                'nom' => 'TOGO',
                'prenoms' => 'Komlan Pascal',
                'email' => 'k.togo@benin-security.bj',
                'password' => bcrypt('password123'),
                'cni' => 'CI-1234567890',
                'date_naissance' => '1985-03-15',
                'lieu_naissance' => 'Cotonou',
                'telephone' => '+229 97 00 01 01',
                'telephone_urgence' => '+229 96 00 01 01',
                'adresse' => 'Akpakpa, Cotonou',
                'categorie' => 'direction',
                'poste' => 'directeur_general',
                'niveau_hierarchique' => 1,
                'type_contrat' => 'cdi',
                'date_embauche' => '2020-01-01',
                'date_fin_contrat' => null,
                'salaire_base' => 500000,
                'numero_cnss' => 'CNSS-2020-001',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],
            [
                'entreprise_id' => 1,
                'matricule' => 'BSS-002',
                'civilite' => 'M',
                'nom' => 'AKAKPO',
                'prenoms' => 'Koffi Jean-Marie',
                'email' => 'kj.akakpo@benin-security.bj',
                'password' => bcrypt('password123'),
                'cni' => 'CI-1234567891',
                'date_naissance' => '1988-07-22',
                'lieu_naissance' => 'Porto-Novo',
                'telephone' => '+229 97 00 01 02',
                'telephone_urgence' => '+229 96 00 01 02',
                'adresse' => 'Fidrossè, Cotonou',
                'categorie' => 'supervision',
                'poste' => 'superviseur_general',
                'niveau_hierarchique' => 2,
                'type_contrat' => 'cdi',
                'date_embauche' => '2021-03-15',
                'date_fin_contrat' => null,
                'salaire_base' => 350000,
                'numero_cnss' => 'CNSS-2021-002',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],
            [
                'entreprise_id' => 1,
                'matricule' => 'BSS-003',
                'civilite' => 'Mme',
                'nom' => 'ADEKUNLE',
                'prenoms' => 'Mariam Chloé',
                'email' => 'm.adekunle@benin-security.bj',
                'password' => bcrypt('password123'),
                'cni' => 'CI-1234567892',
                'date_naissance' => '1992-11-08',
                'lieu_naissance' => 'Cotonou',
                'telephone' => '+229 97 00 01 03',
                'telephone_urgence' => '+229 96 00 01 03',
                'adresse' => 'Cadjehoun, Cotonou',
                'categorie' => 'controle',
                'poste' => 'controleur_principal',
                'niveau_hierarchique' => 3,
                'type_contrat' => 'cdi',
                'date_embauche' => '2022-01-10',
                'date_fin_contrat' => null,
                'salaire_base' => 280000,
                'numero_cnss' => 'CNSS-2022-003',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],
            [
                'entreprise_id' => 1,
                'matricule' => 'BSS-004',
                'civilite' => 'M',
                'nom' => 'HOUESSOU',
                'prenoms' => 'Antoine Didier',
                'email' => 'a.houessou@benin-security.bj',
                'password' => bcrypt('password123'),
                'cni' => 'CI-1234567893',
                'date_naissance' => '1995-05-20',
                'lieu_naissance' => 'Abomey-Calavi',
                'telephone' => '+229 97 00 01 04',
                'telephone_urgence' => '+229 96 00 01 04',
                'adresse' => 'Kpodji, Abomey-Calavi',
                'categorie' => 'agent',
                'poste' => 'agent_terrain',
                'niveau_hierarchique' => 5,
                'type_contrat' => 'cdi',
                'date_embauche' => '2023-06-01',
                'date_fin_contrat' => null,
                'salaire_base' => 150000,
                'numero_cnss' => 'CNSS-2023-004',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],
            [
                'entreprise_id' => 1,
                'matricule' => 'BSS-005',
                'civilite' => 'M',
                'nom' => 'AMOUSSOU',
                'prenoms' => 'Rodrigue Kévin',
                'email' => 'r.amoussou@benin-security.bj',
                'password' => bcrypt('password123'),
                'cni' => 'CI-1234567894',
                'date_naissance' => '1998-02-14',
                'lieu_naissance' => 'Cotonou',
                'telephone' => '+229 97 00 01 05',
                'telephone_urgence' => '+229 96 00 01 05',
                'adresse' => 'Mènontin, Cotonou',
                'categorie' => 'agent',
                'poste' => 'agent_poste_fixe',
                'niveau_hierarchique' => 5,
                'type_contrat' => 'cdi',
                'date_embauche' => '2023-09-15',
                'date_fin_contrat' => null,
                'salaire_base' => 140000,
                'numero_cnss' => 'CNSS-2023-005',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],
            [
                'entreprise_id' => 1,
                'matricule' => 'BSS-006',
                'civilite' => 'Mlle',
                'nom' => 'YAI',
                'prenoms' => 'Lucette Dénise',
                'email' => 'l.yai@benin-security.bj',
                'password' => bcrypt('password123'),
                'cni' => 'CI-1234567895',
                'date_naissance' => '1996-08-30',
                'lieu_naissance' => 'Ouidah',
                'telephone' => '+229 97 00 01 06',
                'telephone_urgence' => '+229 96 00 01 06',
                'adresse' => 'Ouidah',
                'categorie' => 'agent',
                'poste' => 'agent_mobile',
                'niveau_hierarchique' => 5,
                'type_contrat' => 'cdd',
                'date_embauche' => '2024-01-01',
                'date_fin_contrat' => '2024-12-31',
                'salaire_base' => 135000,
                'numero_cnss' => 'CNSS-2024-001',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],

            // Entreprise 2: Guard Pro CI (ID 2)
            [
                'entreprise_id' => 2,
                'matricule' => 'GPC-001',
                'civilite' => 'M',
                'nom' => 'KONAN',
                'prenoms' => 'Yao Bernard',
                'email' => 'y.konan@guardpro.ci',
                'password' => bcrypt('password123'),
                'cni' => 'CI-CI-4567890',
                'date_naissance' => '1983-04-12',
                'lieu_naissance' => 'Abidjan',
                'telephone' => '+225 07 00 02 01',
                'telephone_urgence' => '+225 06 00 02 01',
                'adresse' => 'Cocody, Abidjan',
                'categorie' => 'direction',
                'poste' => 'directeur_general',
                'niveau_hierarchique' => 1,
                'type_contrat' => 'cdi',
                'date_embauche' => '2019-06-01',
                'date_fin_contrat' => null,
                'salaire_base' => 600000,
                'numero_cnss' => 'CNSS-CI-2019-001',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],
            [
                'entreprise_id' => 2,
                'matricule' => 'GPC-002',
                'civilite' => 'M',
                'nom' => 'SILUE',
                'prenoms' => 'Mamadou',
                'email' => 'm.silue@guardpro.ci',
                'password' => bcrypt('password123'),
                'cni' => 'CI-CI-4567891',
                'date_naissance' => '1990-09-25',
                'lieu_naissance' => 'Bouaké',
                'telephone' => '+225 07 00 02 02',
                'telephone_urgence' => '+225 06 00 02 02',
                'adresse' => 'Plateau, Abidjan',
                'categorie' => 'supervision',
                'poste' => 'superviseur_general',
                'niveau_hierarchique' => 2,
                'type_contrat' => 'cdi',
                'date_embauche' => '2020-03-01',
                'date_fin_contrat' => null,
                'salaire_base' => 380000,
                'numero_cnss' => 'CNSS-CI-2020-002',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],
            [
                'entreprise_id' => 2,
                'matricule' => 'GPC-003',
                'civilite' => 'M',
                'nom' => 'COULIBALY',
                'prenoms' => 'Adama',
                'email' => 'a.coulibaly@guardpro.ci',
                'password' => bcrypt('password123'),
                'cni' => 'CI-CI-4567892',
                'date_naissance' => '1994-12-05',
                'lieu_naissance' => 'Daloa',
                'telephone' => '+225 07 00 02 03',
                'telephone_urgence' => '+225 06 00 02 03',
                'adresse' => 'Marcory, Abidjan',
                'categorie' => 'agent',
                'poste' => 'agent_terrain',
                'niveau_hierarchique' => 5,
                'type_contrat' => 'cdi',
                'date_embauche' => '2022-07-15',
                'date_fin_contrat' => null,
                'salaire_base' => 155000,
                'numero_cnss' => 'CNSS-CI-2022-003',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],

            // Entreprise 3: Niger Protection (ID 3)
            [
                'entreprise_id' => 3,
                'matricule' => 'NPR-001',
                'civilite' => 'M',
                'nom' => 'IBRAHIM',
                'prenoms' => 'Mahamane',
                'email' => 'm.ibrahim@nigerprotection.ne',
                'password' => bcrypt('password123'),
                'cni' => 'NI-NE-7890123',
                'date_naissance' => '1980-01-01',
                'lieu_naissance' => 'Niamey',
                'telephone' => '+227 90 00 03 01',
                'telephone_urgence' => '+227 80 00 03 01',
                'adresse' => 'Avenue du Sahel, Niamey',
                'categorie' => 'direction',
                'poste' => 'directeur_general',
                'niveau_hierarchique' => 1,
                'type_contrat' => 'cdi',
                'date_embauche' => '2021-01-01',
                'date_fin_contrat' => null,
                'salaire_base' => 450000,
                'numero_cnss' => 'CNSS-NE-2021-001',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],
            [
                'entreprise_id' => 3,
                'matricule' => 'NPR-002',
                'civilite' => 'M',
                'nom' => 'MOUSSA',
                'prenoms' => 'Salifou',
                'email' => 's.moussa@nigerprotection.ne',
                'password' => bcrypt('password123'),
                'cni' => 'NI-NE-7890124',
                'date_naissance' => '1992-06-15',
                'lieu_naissance' => 'Maradi',
                'telephone' => '+227 90 00 03 02',
                'telephone_urgence' => '+227 80 00 03 02',
                'adresse' => '、洗牌, Niamey',
                'categorie' => 'agent',
                'poste' => 'agent_terrain',
                'niveau_hierarchique' => 5,
                'type_contrat' => 'cdi',
                'date_embauche' => '2023-02-01',
                'date_fin_contrat' => null,
                'salaire_base' => 130000,
                'numero_cnss' => 'CNSS-NE-2023-002',
                'est_actif' => true,
                'statut' => 'en_poste',
            ],
        ];

        foreach ($employes as $employeData) {
            Employe::create($employeData);
        }

        $this->command->info('✅ ' . count($employes) . ' employés créés avec succès!');
    }
}
